### ISSUE TITLE
Vengeance DH seems to be getting stuck on just casting Shear even at full energy

### ISSUE THREAD

**Issue by jmusick** [Hekili/hekili#2148]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Vengeance DH seems to be getting stuck on just casting Shear even at full energy

### How to Reproduce

Play Vengeance using Hekili

### Talent Loadout

BUkACnvaHJn8GSPD6tpaeczPTBAgIIJJRAQCAFQSUOQkkkkkkEtkUSSSSoEJBAAAAA

### Snapshot

https://pastebin.com/wt6RwgBP

**Comment by Hekili** [comment]
Thanks, this should be corrected in the next release (in the next half hour or so).

**Comment by jmusick** [comment]
This is still happening after latest release.

New snapshot: https://pastebin.com/S3h6NvDC
