### ISSUE TITLE
Prot War - AddOn does not display at all initially

### ISSUE THREAD

**Issue by Kintoun** [Hekili/hekili#2240]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

No primary, no queue, nothing. ReloadUI does nothing. Opening UI and toggling Toggles -> Defensives -> Show Separately seems to fix the issue. I did not try other toggles to see if they also fix issue.
Issue does not occur on my Warlock
Once when I forgot to do "toggle trick" the addon suddenly displayed half way through 2nd pull in a dungeon.

Other Addons: BigWigs, LittleWigs, ElvUI, Details, HandyNotes, MDT, Plater, WeakAuras, 

### How to Reproduce

1. Enter game as Prot War
2. Note addon is not displaying
3. Open options and toggle Defensives Show Separately off then on.
4. Note addon now appears fine

### Player Information (Link)

```Text
build: v10.0.2-2.0.11
level: 70 (70)
class: WARRIOR
spec: protection

talents: anger_management
    armored_to_the_teeth = 2/2
    avatar = 1/1
    barbaric_training = 1/1
    battle_stance = 1/1
    best_served_cold = 1/1
    blood_and_thunder = 1/1
    bloodsurge = 1/1
    booming_voice = 1/1
    bounding_stride = 1/1
    brace_for_impact = 1/1
    brutal_vitality = 1/1
    challenging_shout = 1/1
    champions_bulwark = 1/1
    crushing_force = 2/2
    defensive_stance = 1/1
    demoralizing_shout = 1/1
    devastator = 1/1
    double_time = 1/1
    endurance_training = 1/1
    enduring_defenses = 1/1
    fast_footwork = 1/1
    focused_vigor = 1/1
    frothing_berserker = 1/1
    furious_blows = 1/1
    heavy_repercussions = 1/1
    heroic_leap = 1/1
    ignore_pain = 1/1
    impending_victory = 1/1
    impenetrable_wall = 1/1
    indomitable = 1/1
    last_stand = 1/1
    leeching_strikes = 1/1
    onehanded_weapon_specialization = 1/1
    punish = 1/1
    rallying_cry = 1/1
    ravager = 1/1
    reinforced_plates = 1/1
    rend = 1/1
    revenge = 1/1
    seismic_reverberation = 1/1
    shield_charge = 1/1
    shield_specialization = 2/2
    shield_wall = 1/1
    shockwave = 1/1
    show_of_force = 1/1
    sidearm = 1/1
    spell_reflection = 1/1
    storm_bolt = 1/1
    strategist = 1/1
    thunder_clap = 1/1
    thunderlord = 1/1
    thunderous_roar = 1/1
    thunderous_words = 1/1
    tough_as_nails = 1/1
    unstoppable_force = 1/1
    violent_outburst = 1/1
    war_machine = 1/1
    wild_strikes = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: bonemaws_big_toe = 1
    decoration_of_flame = 1

gear: assembly_scholars_loop = 1
    bonemaws_big_toe = 1
    breastplate_of_proven_knowledge = 1
    decorated_commanders_cindercloak = 1
    decoration_of_flame = 1
    drakebreakers_bulwark = 1
    drakebreakers_gauntlets = 1
    goldsteel_greathelm = 1
    illusion_breakers_waistguard = 1
    primal_molten_longsword = 1
    shield = 1
    twentytwoleague_striders = 1
    valkyr_ascension_signet = 1
    venerated_professors_greaves = 1
    wolfstride_pendant = 1
    wyrmforged_armplates = 1
    wyrmforged_mantle = 1

legendaries: none

itemIDs: 109987, 110012, 133633, 133679, 190507, 192010, 192012, 193630, 193650, 193705, 193706, 194299, 195482, 198584, 199089, 202119

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Protection Warrior
    petbased = false
    potion = potion_of_spectral_strength
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    last_stand_amount = 50
    last_stand_condition = false
    last_stand_health = 50
    last_stand_offensively = false
    overlap_ignore_pain = false
    rallying_cry_amount = 50
    rallying_cry_condition = true
    rallying_cry_health = 50
    reserve_rage = 35
    shield_wall_amount = 50
    shield_wall_condition = true
    shield_wall_health = 50
    shockwave_interrupt = true
    stack_shield_block = true
    stance_weaving = false

toggles: cooldowns = true [separate]
    custom1 = false 
    custom2 = false 
    defensives = true [separate]
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    avatar             = 8   [01]
    battle_shout       = S1  [05]
    challenging_shout  = S7  [03], SR  [05]
    charge             = Z   [01]
    defensive_stance   = 0   [01]
    demoralizing_shout = 7   [01]
    execute            = 4   [01]
    hamstring          = C]  [05]
    healthstone        = H   [05]
    heroic_leap        = MwU [05]
    heroic_throw       = T   [06]
    ignore_pain        = F9  [06]
    impending_victory  = Q   [06]
    last_stand         = MwD [05]
    pummel             = X   [01]
    rallying_cry       = S0  [03]
    ravager            = 5   [01]
    revenge            = 1   [01]
    shield_block       = ]   [06]
    shield_charge      = A   [06]
    shield_slam        = 2   [01]
    shield_wall        = S8  [03]
    shockwave          = S]  [06]
    spell_reflection   = [   [06]
    stoneform          = SX  [05]
    storm_bolt         = SF9 [06]
    taunt              = R   [06]
    thunder_clap       = W   [06]
    thunderous_roar    = M4  [01]

warnings: [#1] Update: ...ace/AddOns/Hekili/Dragonflight/WarriorProtection.lua:1105: attempt to compare nil with number
[string "@Interface/AddOns/Hekili/Dragonflight/WarriorProtection.lua"]:1105: in function `usable'
[string "@Interface/AddOns/Hekili/State.lua"]:6906: in function `IsUsable'
[string "@Interface/AddOns/Hekili/Core.lua"]:945: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1431: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1811: in function <Interface/AddOns/Hekili/Core.lua:1478>
```

### Error Messages (Link)

```Text
No error popup
```

### Contact Information

Kintoun#1058

**Comment by Hekili** [comment]
I can't replicate this issue.  Can you provide your talent string?

**Comment by Kintoun** [comment]
BkEAR5QSZgdnGefDo4ho9ZGXKLgAAAAASSSkkQSLpkkkSBRgQRiElkEACJBtQSCiAhAAAAAAAARAAoUaA

**Comment by Wyste** [comment]
This was on tag v10.0.2-2.0.11, last commit hash for that release was 3d763451629ef977eb21229f70b8f8ea7d49deef . At that point in time, looks like whatever was wrong with Last Stand's usable function was fixed in subsequent releases which caused the warning reported in the issue.

Looks like whatever is wrong here might be because of being on an earlier version.
@Kintoun , have you updated to the latest release of Hekili? v10.0.2-2.0.13b is the latest as of this moment. See if you still have the problem?

![image](https://user-images.githubusercontent.com/5103286/211640971-4d3875e0-2b79-46cd-8899-bd7051641b74.png)

**Comment by Kintoun** [comment]
Still occurring. 10.0.2-2.0.13c

Not sure if related but warning is still occurring

```
warnings: [#1] Update: ...ace/AddOns/Hekili/Dragonflight/WarriorProtection.lua:1105: attempt to compare nil with number
[string "@Interface/AddOns/Hekili/Dragonflight/WarriorProtection.lua"]:1105: in function `usable'
[string "@Interface/AddOns/Hekili/State.lua"]:6914: in function `IsUsable'
[string "@Interface/AddOns/Hekili/Core.lua"]:944: in function `GetPredictionFromAPL'
[string "@Interface/AddOns/Hekili/Core.lua"]:1430: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1810: in function <Interface/AddOns/Hekili/Core.lua:1477>
```

**Comment by Hekili** [comment]
Yeah, that's really strange because I don't get that warning either.  It may be related.  When I look at my build, all of the variables are effectively baby-proofed so it's unclear to me how any of them could be nil.

**Comment by Hekili** [comment]
@Kintoun Is this still occurring for you?  I am not able to replicate it.
