### ISSUE TITLE
[BUG] Holy Paladin Only Recommends Spenders with Awakening Talent

### ISSUE THREAD

**Issue by RenSai93** [Hekili/hekili#2716]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

With awakening talented only get recommendations of spenders even when at 0 holy power. 

### How to Reproduce

1. Be standing around anywhere
2. Have 0 holy power

### Player Information (Link)

https://pastebin.com/cU0u3Edp

### Error Messages (Link)

error message maybe not related: https://pastebin.com/m62VyBbG

**Comment by Hekili** [comment]
Thanks, this should be addressed in 1.0.2.

**Comment by RenSai93** [comment]
I updated to 1.0.2 and the issue still appears to be happening: https://pastebin.com/2mgJZXCW
