### ISSUE TITLE
Hek Stalls while Recommond Defensives toggle is active

### ISSUE THREAD

**Issue by Ronin2x** [Hekili/hekili#2755]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Seems that whenever I have defensives active, the que will hang on certain abilities after I press them. After a few globals it updates and proceeds before shortly doing it again. Showing Defensives separately does not help. Turning Defensives off seems to stop this.
[Hek Snapshot txt 8-3-23.txt](https://github.com/Hekili/hekili/files/12247032/Hek.Snapshot.txt.8-3-23.txt)

### How to Reproduce

1. go to a target dummy. 
2. standard physical dps talents for M+
3. use Feral Spirits or Sundering
4. See recommendations

### Snapshot (Link)

https://pastebin.com/bAGjLXn0

### Contact Information

Ronin2X

**Comment by Rustyblade-eu** [comment]
I to am getting the same issue

https://pastebin.com/fPysCSec is the hekili snapshot.

I play Feral and Guardian, but do not use the addon for Guardian, and this is the warning message from the addon

Update: Interface/AddOns/Hekili/State.lua:808: attempt to index global 'active_dot' (a nil value)

[string "@Interface/AddOns/Hekili/State.lua"]:808: in function `SetupCycle'
[string "@Interface/AddOns/Hekili/Core.lua"]:920: in function `GetPredictionFromAPL'
    [string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
[string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>

**Comment by Hekili** [comment]
This is resolved in 1.0.12a.

**Comment by Shizukanashi** [comment]
this issue is still happening for feral even after the 1.0.12a update. (randomly in combat hekili will freeze altogether and after 5-10 secs will go back to normal)

my warning tab incase it is related
> Update: Interface/AddOns/Hekili/State.lua:815: attempt to perform arithmetic on field 'expires' (a nil value)
> 
> [string "@Interface/AddOns/Hekili/State.lua"]:815: in function `SetupCycle'
> [string "@Interface/AddOns/Hekili/Core.lua"]:920: in function `GetPredictionFromAPL'
> [string "@Interface/AddOns/Hekili/Core.lua"]:1397: in function `GetNextPrediction'
> [string "@Interface/AddOns/Hekili/Core.lua"]:1777: in function <Interface/AddOns/Hekili/Core.lua:1446>
