### ISSUE TITLE
Windwalker Monk AOE rotation just stops and no new actions show up

### ISSUE THREAD

**Issue by Parzifaill** [Hekili/hekili#2764]
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When in an AoE enviroment the hekili helper just stops feeding abilities and after a few seconds it comes back.

Talents B0QAa92LNqySTL5b6fvViRevaAAAAAAAAIJSSiSSkIAAAAQikkmEAJJJhkSkQSiWRSSLJpBAAAA 

### How to Reproduce

To reproduce just go into a aoe pack and starting hitting the buttons hekili tells me and it will freeze the functions every so often for about 5 seconds and then the rotation starts again.

### Snapshot (Link)

https://pastebin.com/RzH4GmN9

### Contact Information

parzifail discord

**Comment by Hekili** [comment]
Your timing might've been less than ideal -- a new version was released just a little while before your ticket was submitted.  Test in v10.1.5-1.0.13 and see if you still have this issue.

**Comment by Parzifaill** [comment]
Will do when servers come up. I will also note i cant recreate this issue on any other spec or class. Its just windwalker

**Comment by Hekili** [comment]
It was occurring on a few specializations that have logic to switch *to* a debuffed target, but should be fixed in the current release.

**Comment by Parzifaill** [comment]
Here is a snapshot from this morning. still freezing the action list.
https://pastebin.com/siusd1dU

**Comment by Sunzor** [comment]
i can confirm that Quickfix #2764 resolved exact same issue for me on feral druid, patch before didn't.

**Comment by Shizukanashi** [comment]
> i can confirm that Quickfix https://github.com/Hekili/hekili/issues/2764 resolved exact same issue for me on feral druid, patch before didn't.

also confirming #2764 fixed this exact issue with feral for me also
