### ISSUE TITLE
[REC] Havoc Opener + following Recommendations seem to be wrong

### ISSUE THREAD

**Issue by Naaw** [Hekili/hekili#2913]
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

According to the sim, the guide and knowledge is recommendations are wrong.

For example Hekili recommends using ESSB before TR (not every time for some reason) and it seems like it doesn't always take "Unbound Chaos" into consideration. In my view the whole Recommendations  seems to be off.

Guide: https://www.wowhead.com/guide/classes/demon-hunter/havoc/rotation-cooldowns-pve-dps

### How to Reproduce

1. Enter the Game as Havoc
2. Do a 2 Minute Rotation 

### Snapshot (Link)

https://pastebin.com/kFdXrA4b

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iauBATUuXJ2zYqo9a9qeD1

### Additional Information

I don't know enough about the programming behind to fully understand whats happening.
I hope the Snapshots provides enough content, otherwise tell me what else to share with you.

**Comment by Hekili** [comment]
> For example Hekili recommends using ESSB before TR (not every time for some reason)

Your snapshot is using Chaos Strike.  Can you take a snapshot when this happens?

> and it seems like it doesn't always take "Unbound Chaos" into consideration.

How so?  When?

> In my view the whole Recommendations seems to be off.

What else, specifically?

**Comment by Naaw** [comment]
> Your snapshot is using Chaos Strike. Can you take a snapshot when this happens?

Do I have to press the Snapshot Hotkey right after it happend and I pressed the recommended keys? https://pastebin.com/mGPVDbmq  I hope it worked

> What else, specifically?

according to the recommendations "The Hunt" coms after ESSB but it's supposed to be before, ESSB gets recommend before Vengeful Retreat (it's supposed to be the other way around),

I just tested again and now it recommended Vengeful Retreat before Eyebeam then Fel Rush and then ESSB: 
https://pastebin.com/qUFFG9Nt

And it seems felblade doesn't get recommended in the opener at all, if "A Fire Inside" doesn't procc

I hope I do the whole Snapshot thing correctly.

**Comment by Hekili** [comment]
> Do I have to press the Snapshot Hotkey right after it happend and I pressed the recommended keys?

You snapshot when it is showing you the recommendations you disagree with.  Make sure to update (again) to the latest before retesting.

**Comment by Naaw** [comment]
Do my Snapshots help in any way so far or do I have to provide more?

**Comment by Naaw** [comment]
This should have worked: https://pastebin.com/Da1BPHrr
it recommends Essence Break before Vengeful Retreat when it always should be the other way around.

I didn't manage to snipe the other issues yet

**Comment by Naaw** [comment]
Here it happened again: https://pastebin.com/q9aW9wfu
should also recommend The Hunt before Eyebeam -> Vengeful Retreate -> ESSB Combo
and if there's another "A fire inside" procc it should even recommend a Immolation Aura before the combo

**Comment by Naaw** [comment]
https://pastebin.com/TjvnwujF
it now recommended Vengeful Retreat into Eyebeam directly after fight opening with immolation aura.

I also updated to the recent version in all instances.

**Comment by Hekili** [comment]
Please update today after updating 1.0.1d -- I will look into it.

**Comment by Naaw** [comment]
I updated and it's still happening. I also feel like it's not recommending Immolation Aura often enough (when it procct).
On top of that it's lagging, might be caused by hekili. 
Had the same issue last Season on first day as well.

**Comment by Naaw** [comment]
it seems like that when ever "A Fire Inside" procct it's not recommending to use Immolation Auro so you basically never get the actually benefit of having it stacked up

**Comment by Hekili** [comment]
If you're having lag issues, make sure your nVidia drivers are up to date.

**Comment by Hekili** [comment]
For the other situational stuff, it requires new snapshots after an update.  So if you have A Fire Inside up and Immolation Aura doesn't get recommended, take a snapshot then and link it here.  Thanks.

**Comment by Hekili** [comment]
You're right that additional Immolation Auras from A Fire Inside were not being tracked.  That should be resolved in 1.0.1e.

**Comment by Naaw** [comment]
> If you're having lag issues, make sure your nVidia drivers are up to date.

I'm using AMD and it's updated.

> For the other situational stuff, it requires new snapshots after an update. So if you have A Fire Inside up and Immolation Aura doesn't get recommended, take a snapshot then and link it here. Thanks.

You did the Immolation Aura fix but I think it's still not optimal because it now just squeezes it in but not when it's supposed to be. According to conversations and guides and logs you basically use all your immolation aura directly in query (with unbound chaos/intertia procc in between). The rest of the rotation also doesn't seem very smooth in times. The opener also seems to be still wrong. It still does the "ESSB before VR" and there's no "The Hunt" before that etc.

**Immolation Aura thing:** https://pastebin.com/cBt3k9tP
**Opener:** https://pastebin.com/mubA4WgN

**Comment by Hekili** [comment]
> According to conversations and guides and logs you basically use all your immolation aura directly in query (with unbound chaos/intertia procc in between).

The comparison I can make is against the sims.  If the addon's not doing what the sim would do, I need to fix it.  If the sim isn't doing what the guides and conversations say, the sim needs to be adjusted or the guides/conversations need to be updated.

**Comment by Naaw** [comment]
Immolation Aura not recommended even tho it's up and there's nothing else to do: https://pastebin.com/QPaNYCSq

> > According to conversations and guides and logs you basically use all your immolation aura directly in query (with unbound chaos/intertia procc in between).
> 
> The comparison I can make is against the sims. If the addon's not doing what the sim would do, I need to fix it. If the sim isn't doing what the guides and conversations say, the sim needs to be adjusted or the guides/conversations need to be updated.

Okay I see. What is the current status on changes on Havoc etc.? It would be nice if more people would report things. 

If you check sims then it's not what Hekili recommends :D Sims for example do "VR-> ESSB" and not "ESSB->VR"
The sims also recommend Immolation Aura more often.

**Comment by Naaw** [comment]
Still recommends ESSB before VR.

Rest is also not yet totally fixed.

**Comment by benj3** [comment]
ESSB before VR is the correct recommendation in the opener with bloodlust see below outside of the bloodlust opener you VR after essb.
![image](https://github.com/Hekili/hekili/assets/1052915/90708101-1456-4e5b-a7c3-989bc6d66ebd)

**Comment by Naaw** [comment]
The fact that its written there doesn't make it right.
Besides that it ALWAYS recommends ESSB before VR.

It's simply wrong.

**Comment by benj3** [comment]
It is correct for the opener, sim will optimise initiative proc in the opener as its a new target and as that is already running there is no reason for vengeful retreating before EssB.

Regarding it always recommending EssB before VR it doesn't do that for me at all and will only ever do that if I already have Iniative running.

**Comment by Naaw** [comment]
There's noone recommending to use ESSB before VR ever.
It also doesn't make any sense because it blocks 1 global during ESSB window. 
Therefore it's a huge damage loss.

**Comment by Hekili** [comment]
> There's noone recommending to use ESSB before VR ever.
> It also doesn't make any sense because it blocks 1 global during ESSB window.
> Therefore it's a huge damage loss.

I think the takeaway is that the sim also needs work, which leads to what the addon displays.

**Comment by N30Exca** [comment]
As today issue on opener persist

After Immolation Aura is popped if A Fire Inside did not proc Felblade should be suggested but it only rarely suggested, after that Eye Beam should be suggested and then The Hunt into a fel rush.

What is suggested instead is Immolaton Aura>Sigil of Flame>Fel Rush>Immolaton Aura>Eye beam

How to Reproduce
1-Enter the game
2-pop Immolation aura

Snapshot (Link)
https://pastebin.pl/view/804d0ea3

Raidbots Sim Report (Link)
https://www.raidbots.com/simbot/report/6XYs63gJdNjGQrikBXoDd6
