### ISSUE TITLE
[BUG] LUA errors after updating to v10.2.0-1.0.5

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#3000]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After updating addon to the newest version Plater-addon broke and indefinitely LUA error spam occures.
It was tested both with stable Plater version from 19.11.2023 and beta version from 23.11.2023
```
798x .../Hekili/Libs/LibRangeCheck-3.0-4/LibRangeCheck-3.0.lua:535: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: ?
[string "@Hekili/Libs/LibRangeCheck-3.0-4/LibRangeCheck-3.0.lua"]:535: in function <.../Hekili/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:534>
[string "@Hekili/Libs/LibRangeCheck-3.0-4/LibRangeCheck-3.0.lua"]:644: in function `rangeChecker'
[string "@Plater/Plater.lua"]:849: in function `CheckRange'
[string "@Plater/Plater.lua"]:5930: in function <Plater/Plater.lua:5810>

Locals:
(*temporary) = <function> defined @Hekili/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:600
(*temporary) = "spell"
(*temporary) = "nameplate1"
```

### How to Reproduce

1. Turn on Plater and Hekili
2. Login as Assa Rogue

### Player Information (Link)

https://pastebin.com/v3Mcyp00

### Error Messages (Link)

https://pastebin.com/8Zn9CPbN

### Contact Information

IIeTpoc#3818 discord ID

**Comment by mnbackwoods** [comment]
i am also having the same issue

**Comment by Hekili** [comment]
This is related to LibRangeCheck-3.0 requiring an update.  I've repackaged the addon in v10.2.0-1.0.5a; let me know if this is resolved or if you're still seeing this issue.  Thanks!

**Comment by PowerShellJC** [comment]
I was getting the same error, and I am still getting it after updating to v10.2.0-1.0.5a

**Comment by Hekili** [comment]
Appears resolved in 10.2.0-1.0.5c.

**Comment by IIeTpoc** [comment]
I am still getting it if my plater is turned on. Without Plater it works good. **Version v10.2.0-1.0.6**
Replacing LRC from Plater folder with your version of LRC did not fix the problem.
EDIT: it only occures for Assassination. On Outlaw everything is fine.

```
35x .../Hekili/Libs/LibRangeCheck-3.0-5/LibRangeCheck-3.0.lua:535: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: ?
[string "@Hekili/Libs/LibRangeCheck-3.0-5/LibRangeCheck-3.0.lua"]:535: in function <.../Hekili/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:534>
[string "@Hekili/Libs/LibRangeCheck-3.0-5/LibRangeCheck-3.0.lua"]:644: in function `rangeChecker'
[string "@Plater/Plater.lua"]:849: in function `CheckRange'
[string "@Plater/Plater.lua"]:6560: in function `UpdateTarget'
[string "@Plater/Plater.lua"]:7681: in function `UpdatePlateFrame'
[string "@Plater/Plater.lua"]:3531: in function `func'
[string "@Plater/Plater.lua"]:3784: in function <Plater/Plater.lua:3780>

Locals:
(*temporary) = <function> defined @Hekili/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:600
(*temporary) = "spell"
(*temporary) = "nameplate1"

```
EDIT2: Fixed in latest Beta version v10.2.0-1.0.7beta2
