### ISSUE TITLE
[REC] Prot Warrior not giving recommendations when in combat when Intimidating Shout is talented in 10.2.0-1.0.6a

### ISSUE THREAD

**Issue by Arrhae** [Hekili/hekili#3001]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With certain prot warrior talents selected, Hekili doesn't update its list of recommendations when in combat.

When trying to take a snapshot with the selected talent build, I get an error (attached as the snapshot link).

Tested impacted talent build:
BkEAAAAAAAAAAAAAAAAAAAAAAIEBAAAASSSkkQSLpkkkCEBCFJSUSSACkE0QSCCQkAAAAAAAARAAKtGAIA

Tested not impacted talent builds:
BkEAAAAAAAAAAAAAAAAAAAAAAIEBAAAASSSkkQSLpkkkGEBCFBRJJBgIJJ0QSCwB4AhAAAAAAAARAAKtGAIA
BkEAAAAAAAAAAAAAAAAAAAAAAIEBAAAASSCJJItkSSSaNEBCFBUSSAISSCNkkAEOQIAAAAAAAQEAwBKtGAIA

### How to Reproduce

1. Enter the game as a protection warrior.
2. Import this talent build: BkEAAAAAAAAAAAAAAAAAAAAAAIEBAAAASSSkkQSLpkkkCEBCFJSUSSACkE0QSCCQkAAAAAAAARAAKtGAIA
3. Engage in combat and start following the recommendations list
4. Note that the list of recommendations does not change as you press the buttons.

### Snapshot (Link)

https://pastebin.com/7MiVMfnV

**Comment by Arrhae** [comment]
Did some narrowing down of the talent builds and the specific talent that appears to trigger the bug is having Intimidating Shout talented.

**Comment by Hekili** [comment]
Appears resolved in 10.2.0-1.0.5c.

**Comment by Arrhae** [comment]
I'm still experiencing this issue in 10.2.0-1.0.6a (including the error collecting snapshot while in combat)

**Comment by Arrhae** [comment]
10.2.0-1.0.7beta2 gives me the snapshot error/lack of in-combat recommendations as well

**Comment by Arrhae** [comment]
It appears to still (partially) collect a snapshot despite the error... snagged it here:
https://pastebin.com/CmWa8Yf2

**Comment by Arrhae** [comment]
Confirmed fixed in 10.2.0-1.0.7!
