### ISSUE TITLE
[Frost mage] when using both use trinkets Balefire Branch and Belor'relos Suncaller , never recomend using Balefire Branch

### ISSUE THREAD

**Issue by Doom4g3** [Hekili/hekili#3054]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For frost mage, I expect that hekili recomends to use Balefire branch before using Ray of Frost in ST, and in the CoC coment storm combo reset, but when I have equiped both use trinkets only recomend to use belor'relos Suncaller trinket and never recomends the use of Balefire Branch.

### How to Reproduce

1. Enter in the game as frost mage
2. Equip trinkets Balefire Branch and Belor'relos suncaller trinkets
3. and start playing you will see that the addon never recomend the use of Balefire Branch.

### Snapshot (Link)

https://pastebin.com/1pNS3s1q

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/w5apvqCZmiFMV8XMboZ1Uk

### Contact Information

Doom#4744

**Comment by mikeshanp** [comment]
Can confirm this exact same thing is happening to me as well. Balefire Branch isn't even showing in my rotation at all anymore

**Comment by Hekili** [comment]
A snapshot is required to diagnose this issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by syrairc** [comment]
Adding snapshot to this ticket rather than opening my own, doesn't seem to be a class/spec specific issue. was previously working - not sure how long ago it stopped working since I personally disable trinkets anyway.

see here for augmentation rec, which should only require temporal wounds on any target: https://pastebin.com/BbZn3qmL

Issue seems to be: 
        28.  balefire_branch ( default - 14 )
        The action (balefire_branch) is unusable at (1.41 + 0.00) **because required buff (kindled_soul) not active.**
        Time spent on this action:  0.16ms
        TimeData:Augmentation-default-14:balefire_branch:0.16:Ability Known, Enabled(0.05):Post-TTR and Essential(0.07):Post Cycle(0.00):Post Usable(0.04)

kindled_soul is the buff balefire provides, so obviously that is never going to be active when you want to recommend the trinket

**Comment by syrairc** [comment]
And this added line seems to be the issue:

![image](https://github.com/Hekili/hekili/assets/401150/3c9fc51c-71d7-4cff-ada8-a1a355f51c1d)

removing it allowed balefire to be recommended again.

**Comment by Hekili** [comment]
This has been fixed.  Good analysis.

**Comment by mikeshanp** [comment]
My Balefire Branch is still not appearing after the fix. What's the issue?

**Comment by Hekili** [comment]
Add an updated snapshot.
