### ISSUE TITLE
DH Inertia issue with popular builds

### ISSUE THREAD

**Issue by Sylvanas714** [Hekili/hekili#3096]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

As Havoc Demon hunter with new patch 10.2 rework  they add a new talent called Inertia which is increases our damage done by 18% for 5 sec , so we want to make sure we have the Inertia buff before all of our big hitting abilites  , so we eye beam to enter demonic fel rush to spend our unbound chaos and get Inertia then we do our Essence break combo/Glaive Tempest/The hunt
we wanna utiilize Inertia to buff things like The Hunt Blade dance we need to use fel rush when we want Inertia but if we get AFI proc we wanna fel rush right away 

### How to Reproduce

1. Enter game as a Havoc Demon hunter
2. take Inertia talent , Essence Break or Glaive Tempest and The hunt talents
3. follow the rotation
4. see the result

### Snapshot (Link)

https://pastebin.com/gWj83K4b  - https://pastebin.com/x0HibQA4  -  https://pastebin.com/8CdgxsVW

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/kk85xbcz2qYZWmPKNnHV4i  -  https://www.raidbots.com/simbot/report/431mvrkiTKqaRKG1tHE5bv

**Comment by Zanetsuken** [comment]
A SIM APL issue (i think) Initially the APL puts EB after FR to proc Inertia - but then it would seem that EB starts to come before FR ( around 1:30)
![image](https://github.com/Hekili/hekili/assets/31275306/3604ecdb-6cdc-47d6-b446-0d4fabcf9039)
My Sim
https://www.raidbots.com/simbot/report/ajtB9mu5FpPncn6wXVhr71

and issue #2988 reports the same.

**Comment by Hekili** [comment]
Your ticket doesn't get into enough specifics for me to make changes.  I need "it is recommending X here but should recommend Y first because Z" laid out cleanly.  Your description seems like it almost gets to that point but then it just ends.

**Comment by Sylvanas714** [comment]
> Your ticket doesn't get into enough specifics for me to make changes. I need "it is recommending X here but should recommend Y first because Z" laid out cleanly. Your description seems like it almost gets to that point but then it just ends.

the point here is we should use our big hitting ability inside Inertia buff like Essence break combo/Glaive Tempest/The hunt and even blade dance but the rotation recommending those combo w/o spending our unbound chaos buff to get Inertia because Inertia buff increase our dmg by 18% for 5s its a waste to cast our big ability without the buff

**Comment by Sylvanas714** [comment]
the rotation should be like that 
![image](https://github.com/Hekili/hekili/assets/62980306/fc8121ac-a2b2-44fb-9966-3007f3f27ffc)
we use Essence break combo only in Meta form but the rotation sometime recommending it outside it same with glaive Tempest we just swap to it insead if essence break talent

**Comment by Hekili** [comment]
None of that changes the type of feedback I need to get from point A to point B.

**Comment by Sylvanas714** [comment]
> None of that changes the type of feedback I need to get from point A to point B.

ok let me make it simple : 

the rotation recommending Glaive Tempest then Eye Beam then Fel Rush then Death Sweep without spending our unbound chaos buff here but insead should recommend Fel Rush with Unbound Chaos active to trigger Inertia because its gonna buff the next 4 ability by 18% which is the hunt then Eye Beam to enter demonic form then Death Sweep follwing by glaive tempest , i wish i got into the point this time 💯

**Comment by Jenovacells1** [comment]
Does this problem solve itself if using the in-game Hekili options of saving fel rush charges?

**Comment by Sylvanas714** [comment]
@Hekili theres an issue with the rotation . its dont suggest Fel Rush with unbound chaos active , you see in snapshot that unbound chaos is about to expire and still its dont suggest Fel rush at all and sometime its stay at 2 charges i dont know why but heres that snapshot
https://pastebin.com/KdWWGJik

**Comment by syrifgit** [comment]
Looks like a buff duration error.

```
player_buffs:
   374000 - iced_phial_of_corrupting_rage            -   1 - 2422.07
   396092 - well_fed                                 -   1 - 5655.67
   374002 - corrupting_rage                          -   1 - 3600.00
   426339 - igiras_cruel_nightmare                   -   1 - 3600.00
   335150 - sign_of_the_destroyer                    -   1 - 3600.00
   387336 - zone_of_focus                            -   1 - 3600.00
   426647 - best_friends_with_pip                    -   1 - 3600.00
   390357 - wafting_devotion                         -   1 - -0.03 
   347462 - unbound_chaos                            -   1 - 1.07
```

unbound chaos has 1.07 seconds remaining.

In the rotation snapshot, it's showing as 20 seconds

```
15.  fel_rush ( default - 4 )
        The action (fel_rush) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +10.00).
         - this entry's criteria FAILS: buff.unbound_chaos.up[true] & buff.unbound_chaos.remains[20.00] < gcd.max[1.00] * 2
```

**Comment by Hekili** [comment]
Unbound Chaos is already weird; it still works after the buff falls off (or so I've been told).  Accordingly, it has a feigned duration.  It doesn't seem to work well for that entry, though.

**Comment by Sylvanas714** [comment]
> Unbound Chaos is already weird; it still works after the buff falls off (or so I've been told). Accordingly, it has a feigned duration. It doesn't seem to work well for that entry, though.

and its suggest another charge of Immolation Aura w/o spending the 1st unbound chaos

**Comment by Hekili** [comment]
> Looks like a buff duration error.

This part should be addressed in 1.0.5 -- the "fake" Unbound Chaos buff that is applied if Unbound Chaos falls off without being consumed is now given a short duration so it is more likely to trigger `default - 4`.

**Comment by Elehiggle** [comment]
> Unbound Chaos is already weird; it still works after the buff falls off (or so I've been told). Accordingly, it has a feigned duration. It doesn't seem to work well for that entry, though.

Yes, that is still true. Maybe the Fel Rush damage is lost after the buff is gone, but you still get the Inertia buff even after Unbound Chaos is gone, no matter how long you haven't done anything.

**Comment by Sylvanas714** [comment]
> > Unbound Chaos is already weird; it still works after the buff falls off (or so I've been told). Accordingly, it has a feigned duration. It doesn't seem to work well for that entry, though.
> 
> Yes, that is still true. Maybe the Fel Rush damage is lost after the buff is gone, but you still get the Inertia buff even after Unbound Chaos is gone, no matter how long you haven't done anything.

and that is dps lose just like using Essence Break or Glaive Tempest without Inertia buff , i dont follow the rotation at burst window because its feel wrong using your big hits ability without Inertia its 18% buff to those abilitys

**Comment by Hekili** [comment]
Is this happening with the latest release?  If so, I need a new snapshot.

**Comment by Sylvanas714** [comment]
> Is this happening with the latest release? If so, I need a new snapshot.

Unbound Chaos things ? no its work fine , but still the rotation suggest Glaive Tempest and Essense Break without Inertia buff 

https://pastebin.com/hSyxHKjN

**Comment by Hekili** [comment]
Do you have Fel Rush disabled?  It shows its not ready for an hour, which usually means it has been disabled.

**Comment by Sylvanas714** [comment]
> Do you have Fel Rush disabled? It shows its not ready for an hour, which usually means it has been disabled.

no! 
![image](https://github.com/Hekili/hekili/assets/62980306/44e26870-02b6-44be-a77d-8bdd9ea5ef9e)

**Comment by Hekili** [comment]
Ok, then you'd just used Fel Rush with your previous GCD.  Is that not the case?

**Comment by Sylvanas714** [comment]
> Ok, then you'd just used Fel Rush with your previous GCD. Is that not the case?

i had no charge left , it was coming off cooldown in like 2s

**Comment by Hekili** [comment]
Had you just used Fel Rush?  The addon prevents itself from recommending Fel Rush twice in a row.

**Comment by Sylvanas714** [comment]
> Had you just used Fel Rush? The addon prevents itself from recommending Fel Rush twice in a row.

sometime the addon recommending it like that Fel rush ->Fel blade -> then Fel Rush again even so i have a charge of Immolation Aura

**Comment by Hekili** [comment]
We won't resolve anything if we don't focus on issue at a time.  If you're wanting to discuss Fel Rush -> Fel Blade -> Fel Rush, get a snapshot for that and post another ticket.

For this issue, it seems that you'd just Fel Rushed but without Unbound Chaos (or else you'd have Inertia).  Is that right?

**Comment by Sylvanas714** [comment]
> We won't resolve anything if we don't focus on issue at a time. If you're wanting to discuss Fel Rush -> Fel Blade -> Fel Rush, get a snapshot for that and post another ticket.
> 
> For this issue, it seems that you'd just Fel Rushed but without Unbound Chaos (or else you'd have Inertia). Is that right?

heres another snapshot : https://pastebin.com/5aVAdYYn

the addon recommending Glaive Tempest even so i have Unbound Chaos buff , instead its should spend unbound Chaos by using Fel Rush to get Inertia then Glaive Tempest

**Comment by Sylvanas714** [comment]
@Hekili hello mate . are you working on that issue ( Glaive Tempest and Essense Break  combo ) just to let me know if you need more snapshot
