### ISSUE TITLE
[BUG] Option not showing

### ISSUE THREAD

**Issue by gaveer** [Hekili/hekili#3160]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Right click the hekili icon on minimap dosnt show options , it shows the quick adjustment

option now show if i use `/hekili`
![Screenshot_9](https://github.com/Hekili/hekili/assets/45834601/f99e3735-cae6-43bc-83c3-771d6f38440b)

![Screenshot_16](https://github.com/Hekili/hekili/assets/45834601/0a0f24dd-c3c6-463a-834f-f7d47beed07f)

### How to Reproduce

Right click the hekili icon on minimap dont show options 

### Player Information (Link)

Not player related

### Error Messages (Link)

No error

**Comment by Hekili** [comment]
This is fixed in 1.0.4-beta1.

**Comment by gaveer** [comment]
@Hekili  i download 1.0.4-beta1 and not solved

Edit:
i downgrade to until solved
![Screenshot_17](https://github.com/Hekili/hekili/assets/45834601/043a3c24-bce8-4380-9c24-56e96aa0be6b)

**Comment by Hekili** [comment]
Try 1.0.4 that I just published then.  It's definitely working here.  If it's not on yours, please check for error messages and add to this ticket.

**Comment by syrifgit** [comment]
Was not fixed in beta for me either, will try release version when it shows up on curseforge
