### ISSUE TITLE
Seems to not show hotkeys without re-enabling hekili from dropdown and it giving errors

### ISSUE THREAD

**Issue by ghostedstep** [Hekili/hekili#3202]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

![WoWScrnShot_031924_181058](https://github.com/Hekili/hekili/assets/95735999/e1441725-2e64-4525-9471-a0c4ab820e8d)

### How to Reproduce

No idea but there was others in the discord with this error and I was told to open a ticket.

### Player Information (Link)

https://pastebin.com/88QHEyvp

### Error Messages (Link)

https://pastebin.com/Mku9Wpz3

**Comment by ghostedstep** [comment]
First time doing this/using pastebin so if I did something wrong sorry. Just wanted to help give the error code since others were having this too.

**Comment by Elfykins** [comment]
78x Usage: local result = C_Item.IsEquippedItem(itemInfo)
[string "=[C]"]: in function `IsEquippedItem'
[string "@Hekili/Events.lua"]:717: in function `updateGear'
[string "@Hekili/Events.lua"]:316: in function `handler'
[string "@Hekili/Events.lua"]:60: in function <Hekili/Events.lua:52>

Locals:
(*temporary) = "Usage: local result = C_Item.IsEquippedItem(itemInfo)"



Also getting this same error.

**Comment by thunderchylde** [comment]
+1 on getting the same error:

```9x Usage: local result = C_Item.IsEquippedItem(itemInfo)
[string "=[C]"]: in function `IsEquippedItem'
[string "@Hekili/Events.lua"]:717: in function `updateGear'
[string "@Hekili/Events.lua"]:316: in function `handler'
[string "@Hekili/Events.lua"]:60: in function <Hekili/Events.lua:52>

Locals:
(*temporary) = "Usage: local result = C_Item.IsEquippedItem(itemInfo)"```

**Comment by Hekili** [comment]
This should be resolved with the latest release (for 10.2.6).

**Comment by Imonlyalright** [comment]
> This should be resolved with the latest release (for 10.2.6).

I don't think it has, problem is still there with 10.2.6.
and just tried delete it and re-install, not work.

**Comment by Serenelol** [comment]
incase this is still happening to anyone else (still to me), i found the line it was erroring out in events.lua and just tried this and seems like it works, at least for time being


```
     for set, items in pairs( class.gear ) do
            state.set_bonus[ set ] = 0
            for item, _ in pairs( items ) do
                local itemInfo =  GetItemInfo( item )
                 if not itemInfo == "=(C)" then 
                    if item > maxItemSlot and IsEquippedItem( itemInfo ) then
                       state.set_bonus[ set ] = state.set_bonus[ set ] + 1
                    end
                 end
            end
        end 

```
