### ISSUE TITLE
UH DK - San'Layn. Buttons rapidly change/disappear

### ISSUE THREAD

**Issue by nugletking** [Hekili/hekili#3856]
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DK - Unholy

### Describe the Issue

All recommended buttons rapidly change/flicker on and off (it will go from recommending the next 4 things to just 1 thing) making the add-on essentially useless for this spec/hero talent combo. 

### How to Reproduce

1. Be an UH DK - San'layn. 2. Hit Dark transformation to get the "Gift of the San'layn" buff. 3. Try to follow rotation - you will see buttons rapidly swap (and sometimes disappear) between death coil and vampiric strike. 

### Snapshot (Link)

https://pastebin.com/cmKSppSn

### Additional Information

Im not sure the snapshot will be very helpful because it seems like the add-on is rapidly changing what the priority is supposed to be, so at any given moment it may have a set of recommendations, but it changes so much that the add-on basically doesnt work

**Comment by syrifgit** [comment]
Can you try to get a snapshot of the 2 abilities it is swapping between? 

1 where it is saying death coil, 1 where it is saying vamp strike?

And if possible one where the buttons are just gone?

**Comment by nugletking** [comment]
ill try. it tough to pause it at the right moment as everything flickers so fast haha

**Comment by nugletking** [comment]
here is one where it is just recommending deathcoil and all other buttons/reccomendations are gone (no need for pastebin)

Unholy; Primary - Death Coil(0.00)

there is no text after that

**Comment by nugletking** [comment]
here is one where the recommended button is vamp strike:

https://pastebin.com/pygqz0Ca

**Comment by nugletking** [comment]
here is one where the next recommendation is death coil:

https://pastebin.com/2HERzysy

**Comment by nugletking** [comment]
and here is one where all it says is death coil:

https://pastebin.com/cpgphNsS

**Comment by nugletking** [comment]
a version with no buttons recommended:
https://pastebin.com/nR6i62qY

**Comment by nugletking** [comment]
I have a hunch (no idea if its right)

outside of dark transformation, being able to cast vampiric strike is a proc that is consumed after casting vampiric strike (it goes back to being scourge strike after that use). but during dark transformation, scourge strike becomes vampiric strike for the duration of dark transformation. I think it may be possible that the add-on is treating casting vampiric strike during dark transformation as consuming the proc, rather than thinking of it as a replacement for scourge strike during dark transformation windows. so it says 'oh we have a proc - lets cast vampiric strike and then continue with our normal rotation' but then after you cast vampiric strike, the add-on is like 'oh we instantly got another proc - let me readjust the recommendations', hence the rapid changing

**Comment by syrifgit** [comment]
> I have a hunch (no idea if its right)
> 
> outside of dark transformation, being able to cast vampiric strike is a proc that is consumed after casting vampiric strike (it goes back to being scourge strike after that use). but during dark transformation, scourge strike becomes vampiric strike for the duration of dark transformation. I think it may be possible that the add-on is treating casting vampiric strike during dark transformation as consuming the proc, rather than thinking of it as a replacement for scourge strike during dark transformation windows. so it says 'oh we have a proc - lets cast vampiric strike and then continue with our normal rotation' but then after you cast vampiric strike, the add-on is like 'oh we instantly got another proc - let me readjust the recommendations', hence the rapid changing

That's already accounted for. I am having a look through the snapshots right now.

**Comment by syrifgit** [comment]
I think I found it. There is a typo preventing the vamp strike fishing action list from running, I think. This should at the very least solve the "no recommendation" issue?

For a temp fix, you can import this fixed pack and try it:

```
Hekili:S3ZAVTnss(BX4quKYdfrARepdSnWSdMdydwKf4C27(MPOePS5fjsnKujJxyOF7x3nF0pyvD3KI0ojNXaKjrSz1vvD11B29no385BUoWpp8Mp5oZ9Sz)I78PoND27N)HBUo)(DH3C9o)vFX)wYFj2Fl5p)xX3LS5E6pF)Me)a6RNLSpDf5r3LNVl7xF37Unk)U9lNUkz77YI2UFJFEus8Qu)150)9Q3DZ1l3hTj)VhFZs45MaYDHRi)6CxcuJccclgAy2QBUMo03o7836E(BoSy2V82zZl()oZ)1dlUoA7VFyX(DuOE4Jh(y1GN9b2Gi)HJdzy)l2acoSyxAusAu(9hwSonzB57x)EF4TUNsg9NVl8WI)h)uYFqOSO4BUEtuwEgL09tc9YcZ3VJ8p(eJxgg7VCtyWn)nYdxrjCY)p(EVG4GccinAxXV(Bj)bz(yV71KFnpmnY)MRp5WIGq)8788Jd8ccx5F)08OvFjk(2dlgDyX4dliJi3FtyC(0L7tZYjpXlljnmBA5mZghFqFnAtO3QK4C)BjtlFqp8q1m9L4OBVlF66VLSpoimWl3p92W8SdlU6YdlwD)kY7hghUnkmZ6368IrM6hf4f(vkA4heqWW)IY3yiO6Jsd36hftE2fxsxJ0pMRoSy(HftUjNiIGWZzOLhrmIGCPIm4GWL7xVE6Q7OGYlzTx0QqV80KnBw6htwm3K8TP73XMFBgkhVpS42vbt36)xKzJX0k5iu5ccIEkcIUomJIz0vX80OVekIRRss2eK8Ty1frXjDU1lkklLCcKJcS3BAwozlFXkXzfqxzyzRUp)UqcAqicyQ9mfQvsa)R(K)g5jt3rOpk8s3hhTYBxY3ctz4fB6Y2t337fKKSTAMQ4zH7IciuXk6mn)y4R(7sw5V5(DzHqlKwWJiSOzwTaCHc)hMT9(UY2a5n01MGmpIokDANKLTaWRMBEqygxviWuOMs3M3sPQt0QHynLt6P8AtWaFBuTqNBUiqHYzP1)tfK6v1glRBqpNysbCQx4OOtjfzbqiW49k2m(us8BjMtE5g)7jqGzb53ljKmDAd3ZmA75NL5VFtU4kkkUn2e6rPrx2qTrn1P1l5gSlnXo1N2rbgXSRQvGAgZ47YbSnljtPokfgXe(ctGF6xiMu8JZwNKUL5OKE1NbjuemDpft92TX)29HmKGt5f2ekxbbgDA4AI3c3rHDbAxs2Btsxgfq8fs1rcMqWTrRZPMaj699Y8JPcGvBfkF)S97cj(Jq29flbbkoqCUkl3BnztzQ88x(8LBsscarWjnD7PuyE5gMQwPLh9JquufGXZxMaMuczLf65VmzBuCXOHMynJsCYBom(uZLns2NVKy47l6SYXnGz1wcIfJWc9GN2wdqqWuap40I3MOTllT(Sj0)RAn(a7A8Vx8Ew5wmKApRnBkk)gTDxAYxdPGNorRsI2uT6jSFT(z6vkzZ8Es7MArNEu1pyJtpYO0UcL5w5hy3DdCiCoJlisEUxE02QyJmtfDwMNZVWIWO2BlIIR0WaDY87sQKLee5VM9AIMZfWd6B(vbx3PMEDAQJkB)2TK9F3sOUK7jyTKgQA2Q6OeTf((zck)kC)bqpzPE)tNvGjOJRgY05FxiXDS0T37D7Dj73mTGKyWr5jsURD6mH3MUEd)28NG)2cABvFDifXvVFPpCltYaDlTyy6vcnwqOnJzhooU2PbyD11lcLlTRs2U1NkOvzdMOPiOdw2UaWFhZWgr(ZeRHWzMlOQNUelmd6vG2nEMj0zME0b3TRUHoc7JGzY0Ds91IbN0u2HtC)N4TrY61EK4ArumlgINqCS(BjHpUmJ4zOhX5UveeKPMywLZeC7zxuSBH7Jbj4arZ8e90e3PxrupgUztH2sdXLQMbNJkS0cTL6cOZCo10Ay6kydtQ587F(hhL)kWEdGLAPV7YbwxCBPBUd8O5TIrNoCTZPdBxZmkJBskTo3w1SOV6VDxukDVjJ6k4q1HMbfSjtWgGQi8vciI)sil54n2zlTv4ZLd8WcXKAuvLH13N6VHUpLPcKGrBtBYriy3wQXoIuz14vtwUQYsU9VgQrjlvogTGiMckmVk04TJSUE9rlYhNQPkLqpJ2gYqFN5swbqzHAYtuoDT)UW0K9zfUqSnkpxMRpgZENKLqjBKtANdkoZQKcWqhn68kL)CaDJV8HEoEub)SQfs7CIgySgwymniPDRQJsCpBjEpn3zkNlUpLX6oS4vedYtN7iMGQsZ3brz0PYZpjVVZtH9y1ebwN7mzlL8fe(l20NEl92xlujOJZu3cMaflm(cMuLQuMaTblv6zQSSdhMssnqU35wXfTzw6qGwTG31PqPSe(tKKr1TrKov1pqbfAgyRTZV1HjFUyyYnanVMYfgLz0u1Efx(EfPWJprAm35N5vno2uPwjbiYGkPOyXAuHXmsibBsYfuoQXxSYX4QvbQ7pQkqD)UubQESYgfOUdIcu32Qa19zfOM4D9Lcui4)yQafJ(6BfOUkkqDSqbQJ9kqD7IcuxDrlc5b6jGQUL0Hw)8a)T(3sJXEGSMihdIoHeB0tpYYaASFwTzkTT0CwBGWDw)RE3LN9y7O8(KFpY2aUAs86qrR2D7oRcpbvZyopToZH8yblLjqESaTHZTdB46dTppnca2pR2mLpVHRnO5p(B4ClYMxMFS36OS7Oj8tBv8LtVVsPnRByP)Zsq1lLB4mdvD7e957)eKSFsBhxoDv0DcARuvJMvuUGc0FkmWBzuqaH0RwBX6Oa8kqvKO1P3f6Vj)UP7OzOLv7X5qlP02AsOEqeNvjpZFxrQZWR9Jn8ez8fV25JnvqEQ3wNEyXB16sSPSzdN9)kbEt0IAj8)0h0uwmd55xhPOPucIDPjTXQ0TndQzXW2QP0BG20Cqi7w0LV4g9oQL8RN7u0bOtrTPTjRw4E6Bi03RAOULneQ2A1)CFp2P(ESSisVRoBtSq71rNe081nhA4sINkfuTHrwq6lPctkdEcip4XQnm)EJtW35(JFxHMLRZiNOZkkg3iSg6wJptIwlxTSXhJJsADJuER1TPmnEqAkqu)pgnBS6Ygy1ZA6lFl9o9e9nucdf5vTL6jKx6oZXlmR9oWA0dQZe2UlGZ8ovT2slCtDiXCaC0sJJVatNgVe7HVshzMgUBNyScJUeW8RaNgY50myRAKq8solmpATiYuidYZSUsxOI5OfDzt9zunp8wwqAB()DnErrrVIobqOFce8(SCK0)2M9eeBdvH3SY)5nx7aTZwGYGGt1ekPpdNfW95rppauZZ7H5n24GAXBprlLRQuWwkxS714uUPA54mZcPYlQ97VgCYEIkBbEMm9DAn99bivnwsFIBXLCASBXAk7elurPMyV7Zo2XBUOoLpYwNQgOO5jUYD12wTeDstYZdJ9Yt2V6o7JzXrcg6dUrti(LX900cZCBXdTBbu14BTicGQ7gUeGfWILbanVY3lLMOvlbPA6XscQYWUIeVGF1IcbGUudoGc3FWeKyk340hXdP1rRIYRLFflSD50O5lHPAWawHCLqv6lrdzli8R(ejfz))NuJwHIbWd6RvT)gQz3RCp)ryzUYRE8L6YSVwMp220pLp3lLnc5ZMe9ZKGEUxkpYEPuBdwmYMpwil6wRzt)WPvtyJX27fmxt3d89r7xnm8C3UYZ7JAM(JqhBisGednE1kpQRgN2mi2Kf0aknBrMNBoeZtPTjmC0Z1Q2KfKFiQv9q0CiIBI6H92aqPD7T7dDQpnYA2pR2mLpV3UnO5p(7Tf6df9Lna(GKGxYGuwndGQxWjAovx4sL45)3oU9fgl0qJin5FhEO6Ae96HhenClNilNdgoVAWXUsk7kcLFvsA6(DLUxILqBdDltywwy8QWkQPOkO)5(WWy1IRpcTloKihiEJ4AuV4HC9N2kAHb6A37yYCsZ9kDSbFmMesXYWykJV45dTaVeFVYpKIarp7hB9YNj(JSMwTqR2SlCHKQGM50y7OpVM6Re1pITnvNbSMnm2w4l46wwYOku9q0ObTBTwudmrEJSHB70uR4emfFN3XYFEL2Q19PFPR8je8S6SQP)63SwEU1aNCljRyqLszK2IPFI231S3hUg6OuDiDVyHXX1s0SEjsPpU0A6ff9nVf40wHucTFIMmDv3ilnntsJtI4BIxqur4sWTZf31Nh7dfpg7kkE9MigTqn2KrClIFQzu7q9pnTg2tyVyH0aG4E50b1oM8WqyiACrVyh0wgl2kZlxWdT3cmaiEjXZyhWMTAxA4QKTl95bpvn(coonitr2OMcA04etIdCwMnU5AxnTDaCbkzL7sjJf0tRikROrkpIYMUnISnJD2iToLaV9P0Zy3KTSnFzqVaAvy4fhvj9UAATaBObxD0GBBPb3wsdUCAOJ1(MZnQsZUKc6bB1GxhuHxHsmc4rjVUWoDhlfoNtPL(69vka6Zvl9P6BClPphVS7Jx1Ms3P3VlOupYleZlGdnGpGlRpOSRssbG1MUnFqqsDIN0zPXztNl3cgQU43Y1fxZRlQ5I2U1fWdrGbCDX481L1f73f1yDrngPwUUuLUDtfkqCtJXvozJcntfFksQ6XR9Pe8hBA54DgQF6ewPDht)89NZ6kDuZy1JeaEubAryv1F7YOx0MVUHL3cXnHSFBcdrDMnRk7qtyE9pUrvwTJaDSIav91aNaDSIaDaiqxucuww2HR6Nkj7mRBIYifqQns0MknwdsJ6BTcpqhTLt97CvK)gWgAI7P5k6HlyoXqlrLKsoh(VkFFbQsTj6CR)IrlZyJ(46RcFViKR17tVxqc71SOFPKj8zJXi9f7ySv1aIosRQWI0b0BhoOsU0mPsXLUD(XydKHInZTmsjKIWykJigNzUGfFi6tvsTebj89WukA8ZVeboPESse6H8qkrGnZcse1drFbCyWRmjkzehuIVn)oHpXh(kQyoaKwnBKHaXa5Hs8v9lPoTMErHStZs3tM3)7(GB3svLAQ6qoN)tLKTZ5hJ0B1BpmsOoNlyWlEvinpHB8iEOB4dRhbBkxaO284nAn9zn6ZC5hZ4Ynm9UB)MIS3IxHMkDKRJsdz6v)PxfjoL2Dzmla8Wi(PDI5Yd1JqF1TuXXlf(0WqvDQfflVI34kQ9VLL8XuAE9RlH1Xv(k5Rtj9Nwca18XubYpNhOhEi8yRWwD(6FmvSYe2xxa1xjMJ6oqjfYQmPadN8EwwFPJTOx)uwPkSAnn2q5MOGWy9MaQ(J5soH)fTRcRhRkjHSajVa8QdL3rxTROtglTeCDJgJx6Og)oVxbAOzb0RtzBEqgGaUnqW)cgTUuw6AWpJfSIEo4WUeg0PAV(2p46MxPQ)n2llNZdgIJFo3ljmIDdqiijQ5sIiODxdKw(oQQvzFpgNXLsaKTQJEqVCNprNaT1KzLWM40NAhqzrZ10yK8EjZPmJx6kROCZU0SJzmClvaVp1qdic03xcU8a0WwyMgmH8MBRiCrtnAGAUpGJBabpGszwJWSD3WiKAecySgWRlcsOimB4QfNMOyiWJydk8FhAO60YxCCKONoS43wv4j7)GDlnxdtAOvEf)dp6f4CX14CzUtRuFNPx6PubG66v1yVM(VxLZUEASAAL(ep1MacUcQEBYfNySVnkTaOkvUAe50((c3xAAd1upHZ0Nb64z7zjINeBAd4X4YXaGv3auLRJIjDj77NVlytj)PrLkowguNXig2O6UG24t7Y6qX9sj9nWJ5cAn)0kpb19LgWlVLYGKCGAML4k)MPNIU4A0Wr3XAq3AlxOh6DADPHojJB4kuXjEFvbYA7Id3Xr6lHRiTlRp2JcSj3(wtRopjL7vSOt4n0VE(b3lf2HM(jJ9Cl)wmSRlbF9bXB9T09XAn8vDYYszz2NVtvwwVzoS8JmI(g4MIqXgJ676acLFtX)DnjQ9m64)K7m3ZM9l0ptQV5NsdXK4FZNVJeKE02DjPex7jlkhw8Y6n)V8WI0W)CFe7UfnlH(5h6VppHSUr)bIR1KyZZME4J)JiAPsD(vAwWIjZg7XVemChciZtWEyfXsg0yN)AIjilF8OOaz4ZxfoKp8rakV0uz7OB3ba7kG8PdgKpdgY1nSScqB0iZwcpH0kParGeozjmLsDKcubtR0tmCBKrjfyJMyQhp4dVxG5UsVSva4C5rbj1CY9y5MIEAoqvluePr7yhi6TuQ2uJDgGvSsLnGWQbVbyvMbT3sSpvZdI0DpopGlTTwB)qyLdeZQIVUxqVEqjHw4R2D)kGh7dt3Y929YggeypSy(qb9YEMdORgRNbnD(4qdEtCLEtASVr8bg8M4l8QNOkN0OSkgr1HCNtjn28icQbxaCidiWTaSI9knaivESn2O6fMmcS7jfipYqV5Ai6(e4XmOG3exP3up13i(adEt8LJq90J6oNMAPX0GaoKbe4wawTQNA8yjCDUz5HwOkDqbUfG9i0t3aO9O0gcS7jnPiqV30i9mN57m4)mNFq5mVVxvFpOa3cWEe2gAa0HKj3RIFiqV3e)EMZ8Dg8FMZpqCgW0mkuk1x2QmnIKXb5Jpqfue(Sf0agk0vn9cg(C5ZgIYCnuWDi4b87vnfq28cxZsik1T6kafSt2TeU9MgLNi4))px9siKgJBLr0LftG1ydFlgp8aMMIrNOPpCgHZlhP5Z2yKUVyJjJgFIUTT1Ok4thXZQeEN(CLZ8xmES7RWX(jVM)4MRQIpfC5zYebQaveUMsqhbNAAoKhrAPsI8zPifo)7gAo)JOu0GtlVuNhGz5TZ1kKYalDoxd7eG8zGTQIuKUn4OCQulKfpkRvT9bCkxRcvexmb2OPaCnTQP6CGKFKFGMdqXU6VzI2j59OvBc5VtuyHzLRmpl5Q9qaiybGECsZpQqTNAylTZbWL5MYCO56EZG8R4hFt7eH)jRhDoQcbnOa3cWEevzQFln4GcCla7rKBzSA4jCNubHKcp7PaCDtKAqbUfG9iKxhY6S8CfOAjS)XMZm0W)zo)GYzWQWORgnSU4AyFKax3m9nOa3cWEe2vhMQaPf290MJFmRp2pXCMHg(pZ5hiodCONTmBDi5(6iYwh(NjvBlslwWQDpFo9peFUCVpAWT32ooCWhu2V(YmPDs)4FHjINV4Ve2VbHhlr64a10TsbWezXRy)KJC28dpT4dw)cTuSYOSWgp2sGAb)qDIS4vSFYTLfAyW6J1OEnBxAYQPSBh1Dz6(wNWgxppn0LkV2dElwaowXETtUTRzTrShpOl7yM4JRNNgTRz4G3IfGJDFM2j321S2Sp7d9UNjnGyZWzB1xO4adEtCcGY9RWs0CbZm0i)adElaClelBJQeLjSr3lHDNFmAmQC6iDK6lEr9pbCRcD5S6wQqZITTtGURrOlNnHmvwYXyS3ENtm0mI(MpulZCEVRkRbeR1gBE)KfFSK9n4nXj6vvz9nYpWG3caBEVwNSWEEBvL52InWaKA)Qkt)ey)wyByV9oNyOze9nFOwM5x0gaz10ciwQl39ya9OkiaoM2T9Pdm4TaWuQT4CMU8QDaHnRoglXBBbpwAaWHm9QkdstvXpBfqCGbItlbI51glCMTVbVfa28Ad8ySeVTf8TDPVxw1og5Ng20ob1Run64H1I9WdNGOkIOwfhAJ1Pg4fAUdjN8QXotN)AKDJKNICFrsFVxlnTug3BvwnM8cNzZMmzYvcJeYjzn3bKQiOJre0bebDuqqxjeSsq478vY390Ts(oRwjBIGpARKLiixXNZS(yVpkuSuneyTkkp41FzRQubsnepYYBwa7H8WRcPoqcx5jkWf4YqrfMdzV5GKzSJe2y1RTDYa9FLvrKQoci(tqTv77phXES2NpoWhz)1qSNTtsAyNKOfNG89YEQJ68eD4GmiLxEnS0o6g7JZx(4pxb9qoC0Tu(SxGnI(5Eb2iPsSxGDJqr6ry30lL(e4d73Mw5KG09w9dfmmYmh(4FNTnKcs6LnBXfbWHf07aa6(SBUExAY6i6T8EXJYMw3LkV(Y3vOnM2XCh(i0Zv7RU3u)qwx7EPl8Rv5g9BO3cbxMlhhZByxM7xYDIv0hCEI7mx(DLXIKJV2GHUGyOlcgAUyZkJThWqESmVjz3LSB0)sS1D2B4xA(cCxWs0)MvjXbrSKL(0YVBh1G0WbauZtZAdnwrvkXrKqMnDUaY2IkjoIZ6716pyjCToD79NKXXYlXlLXi(c)WWl7Ps40xYL7sJssJYVVXEmrUPJaV8ysbfAgO6scOoUmjcK6FRZbLskOqZL4XLkrGmuBDsOuYbLCYeTr8iWFR)T0RdZExkP5tQwALX2RUuMyOUZuI3eSDl)cC8Wh)piop18MzuC4RuUhKkiYkmXIHk(TC)gQ)wRYj0B06lH9fZmabb2jDfALjSZ8a5xuj2n2YJvnli5r(sxDvxj4(NPzWgEqxbFNq(lDSc4DaVTcYS7vhjGRaelO96RORMV(vxE6OtcGVj6eoyDGVLaVWzMDtolrbAickwmgblE4bMAp1NUF3OaDx8FxD5yPR8Vxr8cqqDNo0TDCjrqQCl0XvxuEMjcS85mcp(ZrNO1xa2fWN(dRj2ZmFT7DHH5HnOxBHKwXPdKoX1A6T161mbxufMmJc)2)8p426ilYKPr6wd(nsxAWftHU7P4RiZiMGjy6Xgb5Vy1j6uTDq6ZOrmlkyvIUvxaZmfm1VWocuPZbr0JqY7s(MOlFTJonC7xpYMHvjqD7Qav0q9gHgct0WJUaIhvQCOXDSDXLpEhqaDl5x42volQeKozcclSK8utUdJ6gbD(UvRtQqMV(oQxcXluhRkrPzMQpxZKLORdXrrqxRE5lK0kBySY7XjQWpRypxJ7z(sgvJFF0y2VdCZZ)Wdy368xWy8W308elEI(mlYmTvwWWUmyG3q0LapyjFmiyl6HjQQtuuV0LLuulrPlU0TdeQ4gJRPEejddMtseyWYBuCaBFbMZriBk4MHKoAUOcuA9wrABHXrF(dpK6hf4f(vwglccYMg(x0aDgP(Zvc1x64G9SRMpbMnyRmZqA4OgzSrGPwDQY5IwfWNBKXQQDsNa4z2B9PMkS2ioIIUEG3ayALW01sR00z1cT6hjPxUj9tjXV9A)4xs9LLwrKc0xa4KOUiGfWJv6mupbzmJJXXS9S6ycNtZbLAkaF4bFLibCMqw2tYYgTMYj8QEB3zQiM8P(x3WjYcZRCTdVClDhfWb(97SfN5tag(Q(gj7ZxsKm)cKixX)ykTaqE5jEbrHxbFO0YqhuhAYkr4lMpY6d1wH(0O4LqoxAjY16oyAXozARNhPoSq3jal(j)QnN4RMynV60jnwk5GHee12LOcGNO11jXMLOkGsXFRW)aH9ocpKWp2fwi16D7)x7D91CBBdd)ZsFXXATjr)X2nDxSUBx3TD7TDlD7XyRA7eRv)VZwUU9UC(Z(aPOKiPaiPSDAsxZ1xsLTabbb(raqq4PGJxYaX11P9SG3gIQeheIIxW3Ihh0yqUZ7Q7r0u)pI73PvBQnuHDgEfX(ZkmFChV6eX(g5p8qfMrUNkLFAKP0LyC2iNOD2ak4rZ7l0dtWQb8HiyrhO2MzWWw22DpQsPs9B4HXL223qH1Sm0XDPg6I9nrsRL1SRfHY3LaUmf0tiIzzFiPPT)7tEB)gVDF7uB((rdbgDPqA3sxvYb3CMCD)iuQzcWwIgc4oNH6yREnuFNacHI0VGK(yGKkeUpvOP9ChnvWPYit)yb7q)76aEN4NSd8B(xrGJcb7uYJuAaNqaXckEOGIe4HgXcRfQxl8i2Q55Aln3CZjeQpUUeigULpzaKgI7JoMWk3NBclzp(qlGJrnyWEMgAzfIfFIMU4UzPCEpp9YSAg75pI1JgmJhQAdIvSJgBg3vGk0vSixTgBPXrIiMZBYlFcs0g(hdcGvlPXykxi0Uxos(MOFJDkG0757z28pYpUVniGhEGJEXkGxz0RwApT0RPiFXBOJ3PJcw)nKuxKFL6ArS3bhxc(aqYdI()EZK9dVoz)WPGLs)ZMMLTAZpF5L72T7IDl3nL1BphTC(LBwnz2S(b((98VKNDXZbd2TBGX6S4)KNTXH)H4bxFzs8(H7McE74oL78Uq)ExMVaDE5fUk(3f)vont3SF42vVz)We4p2nHvEsS)Y1Xi8TD79U3jb(Ew8Vu(35Ja7QvSlnBQ7eTxuxqKW0loxvV4S4FfE4(HFq5PIjYDUpaoY1UsoNe0G52(HlwMTFyUnfR0MyklOgLPl(8YpbMIFbaewKmJx5z5LAaxrzqHIcHzlgCfUN)I8GvA(kP7RBsdirs57vZUVypf9ITV0JK6a2n0SlqkrEeeZzCIGR8ONjVIAQyanJMAMFjmzVnO1xh4hx(DWuugOQJuwuN1tmFKriAYeeP7LDPABTRAblCRgPmkKIGT18e2r7PSa4I3dY5VfNk1SxWrZJ6smjRP810zj(WP7NzXWPPf8g2D4yjSiF)OX5(B2KHwSEJkyuuJDv0rPiSaC)fcjFe8iaHmpplshsxYCisQpcEK(XbGpOJGrm2VL05SbIJ8WVk8M598InuA04))x705HJ8wJl)HyY6r(vGSH8J4ecHD(KelHzCJUUCmQYJ3QCFiTCoXUEmXnInAAHszHfr4c1d)xoAVQjUqV5V0Q44leLGmhSAe7i(ZGWIG1bgzKvadRuaR)Q5rdD321FLBaYz)QNvc4(6O4(y7K2cb2hqfowVTB2EG0mDt9H2eL0rmcBrTNcUl100gDDbINDYAg5KwxkF23tRlym9HTUGtPtZ6cgTXwx4b)VzW)UD89Zf2ACcisoWgX9gHfwyBKdRvbLkpQ5cgPEYweFzDst)cEOGdlgnHLAKzdyv8lxBk4QNXAnmVJBM2b7nowTGGRmaSUA7SnOfSoefrBg26fJNCx6O0S4(DL37V6XGCaJ(3LUEchsOYiV8rFhzJJXZnDr0aHo21wssJc8MCp3rX1SexwFnNftkHbp6GZQ6pTKM)B5xtHQbx6UlCkC4SJpnPR8WmpAP6h7gEjklFSKQ0u1)t(llNQWQC0Q(Bcmf5yvomi8swL7oKaJB6KKzGmE1OSR7h1v7qj76gR10jwnxZSCyFrNtKgGMELe8iQcyAwTMVSPwkRxkETqxf((S0Z9bU0xs3vz85fcSdbT0sn)55)(14yeWiJOffoPCtJLL5cSZ2OALvjLx6hrxy9i3)zHTrUT2iWz7TR4CR(cdsfsxWPoClHIArS6xYCyxIPCZ5d84Pukh4YzGtMIUNpFD7uYsU3OD21DmxlNygu57GSu9oKNUH91g7X2X0GC108RkhdiFUNsP9jfqQ0TIG4ysciSo9Crn7PhLQXKYQrU50py(kM0gBljRxdJCdENe4gPvNJBUjWJ)W68RUmfsCM4ZbIZYPwA2K55Py)UVc(9ZgnEEVaB55RR4BqsnNbkWAihIVx19Uq1RhwQi18clma1FNofEqwtdJ4eWmLkCQ8xdiHqqpXbmNRKp4bnzX4Ldi6xddYs28P65FmhIEn89YgmpzrcGuEpmJNNUzJnO0YRbk5BxiHcfgoJw)vy7JrdGNLTERyg4YqG(I6uhM3qOQS8NoyXKVSL1Qhyn7O757(moT4pDAaDLwL8GJANeloCumSC(kLjyP8d75MReb(25QnZwMv0NaulMgXdRAjmwfAM4feYweuYp5FXBJAvVPtu0piyGtINDr9FUQLAWhQD(dpSo8r1Og3xXkUfZWUzIRquXv4JJ4k0DXvOCZWXG4kWU4k8ekU0YYDn1ljEU43KxikpBoJG9sEsshIEmYbQtDaN7OHQHPXNgl92gv(FO)7qAHxiH(hv53aV)HCQRoWXMk)rjMwFiTMzNqq5bpDryx2JUntzoexzgPzeDakZHnvz(WS4pLlNVOm)mtzwlPg8CAOCrMQu3DoWx6yB1slcA2pit)M(D5sX3zcFQ1LdA8sdI3qQ6azb4mynEsnv8LIkmEBrXJDgVgpex95LBND6HkkSnyn(iQJ73Pw4C4kHy4T)igoNKC4riuoklTsUSQWZn49QNLO5oTJIRrID6gyh0kFYcJZMFjwcHJ6GYK(eenvITdTVnnItjsrX0nq7Y)lsq5GKLzJpU93TnWGjE7q)ydHhIFZlipkptH3gCb4FwOVXVKPeiY7IcMTuAxxfh5me9SqLgDmOwNXejDv)XosppsFNqChaVcyTYXw9c7kfVXprXuEu5PWgEGLCu8eHhG0vv)2GhqnWu4bHNm8GqxWdc))eEG(m(yXdcF0Xd054Jfp4Wcl)OseNn8aBjHZAQgommUtzW2VKQbRUm(TnvdUQ7zlNzw19om7PtP0)fDVNz6E8Kl8pcfhjCWcDjMYyXFx0TxlJ)YCZ9xQrJRUZj)QvUgTLquV75LUipiF7mMu4IhiJXktqkotl5D9AAF(lUNBtIQsCqFs8w5jrK0KWKRob(26vEvkvQxR9sgxo8zAgVkJwol8nvuoOf9bwMi8S1qncSnbzx2bbzv)cO375YcXrUCVCQ(qSKOpQc45Hh0QouBJKBRw1sEPZlBczLAVhPsit1Hh1UGtUWLfju2zwRAZcPfh0c0J11WXwg5LXJETydAiSaCeKb5klPNSu(oT5FB2hZ2Dy8KpNaRqm2SO4aJqtf)d17yU8d3Quz09Ch75D7njBZMUC9T3Ct68TZ4d)7xNCx2TS)D7)9d
```

![image](https://github.com/user-attachments/assets/c84ab091-90ee-4b17-a46b-c2985c11a4e1)

**Comment by syrifgit** [comment]
I think if you go here before importing, the circled entry is missing for you

![image](https://github.com/user-attachments/assets/ba8fb61a-ea65-429a-8af5-fb84c7ff132e)

**Comment by nugletking** [comment]
Thanks so much for the super speedy reply!!! I am at work for the next while, but will give this a shot when I get home. I’ll reply if there are still issues.

**Comment by sKullsen** [comment]
I have the same issue in aoe scenario as well, I think it's in aoe_burst, where it constantly switches between epidemic and wound_spender.

**Comment by sKullsen** [comment]
what was the typo? maybe I can check if it's the same case here

**Comment by syrifgit** [comment]
> what was the typo? maybe I can check if it's the same case here

A typo in the .simc file which was causing some of the action list to not be included in the addon. See my comments above with the temp fix and a screenshot example of the missing list.

**Comment by sKullsen** [comment]
still flashing for me in aoe.

Here it's picking epidemic, while it was flashing between vampiric strike all the time.
Often ends up with empty recommendations as well.
this is after the suggested import.

https://pastebin.com/PnpFAZJc

**Comment by Hekili** [comment]
This was fixed in a previous release.

**Comment by nugletking** [comment]
the recommendations for sanlayn UH DK still do not work. the flickering is still occurring at all times.

**Comment by Bingo176** [comment]
Didn't see this ticket when I opened my own ticket

https://pastebin.com/Vu26Ke6n
https://pastebin.com/bLUAZVdm

https://www.raidbots.com/simbot/report/itJytWeshazBrjRAXSWQfz

These were in 5 target AOE. Vampiric Strike flickers during Epidemic spam window.

**Comment by Hekili** [comment]
@Bingo176 Can you contextualize those snapshots for me?  Are they taken pre/post using Defile?

Are the recommendations swapping as follows?

* Current recommendation:  Defile(0.15), Epidemic(1.41), Epidemic(2.67)
	* You use Defile.
* New recommendation:  Scourge Strike(0.00), Outbreak(1.15), Scourge Strike(2.30)

Note that, in the context of the priority, Scourge Strike is Vampiric Strike (they just swap).

**Comment by sKullsen** [comment]
I have the same scenario against 5 training dummies with the sanlayn spec. in this scenario, `wound spender` and `epidemic` change constantly place in recommendation, without me pressing any skill.

**Comment by nugletking** [comment]
I think skullsen and I are experiencing the same issue. I will screen record what the addon is displaying when I get home tonight. It’s hard to explain without showing it

**Comment by Hekili** [comment]
Please install this alpha version and advise whether Vampiric Strike, Clawing Shadows, and Scourge Strike all work as expected (and do not flicker vs. Epidemic).

https://github.com/Hekili/hekili/releases/download/v11.0.2-1.0.19-alpha2/Hekili-v11.0.2-1.0.19-alpha2.zip

**Comment by sKullsen** [comment]
can confirm, no flickering after this :) thanks
