### ISSUE TITLE
Nameplate Glow Conflict with WeakAura During One-Armed Bandit Prize Mechanic

### ISSUE THREAD

**Issue by less1140** [Hekili/hekili#4860]
### Before You Begin

- [x] I confirm that I have downloaded the latest version of the addon.
- [x] I am not playing on a private server.
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [x] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

There is a visual conflict between the Hekili addon and the Liquid raid WeakAura during the One-Armed Bandit boss fight in The Undermine raid. Specifically, during the "Prize" mechanic, the coin adds have their nameplates incorrectly glowing when Hekili is installed.

Disabling the addon does not resolve the issue — the nameplate glow only disappears when Hekili is completely uninstalled. This suggests that Hekili may be affecting nameplate glow or highlight behavior even when turned off.

### How to Reproduce

Steps to Reproduce 
1. Install the Hekili addon.
2. Enter the One-Armed Bandit encounter in The Undermine raid.
3. Use the Liquid WeakAura package for the raid.
4. Observe the coin adds during the "Prize" mechanic — note that their nameplates glow incorrectly.
5. Disabling Hekili does not stop the glow; only full uninstallation resolves it.

### Player Information (Link)

Unholy; Primary - defile(0.00), death_coil(1.05), scourge_strike(2.11), death_coil(3.16)

### Error Messages (Link)

No errors

### Contact Information

sleeplessanger#7310

**Comment by chomg88** [comment]
Hekili likely uses the weakauras addon as a dependency, which makes the weakauras addon load before plater
Install the platerloader addon , that should fix it

[!!!PlaterLoader.zip](https://github.com/user-attachments/files/20180281/PlaterLoader.zip)

**Comment by less1140** [comment]
"I'll check it out. Thanks for letting me know."

**Comment by less1140** [comment]
> Hekili는 weakauras 애드온을 종속성으로 사용할 가능성이 높으며 이로 인해 weakauras 애드온이 plater보다 먼저 로드됩니다. platerloader 애드온을 설치하면 문제가 해결될 것입니다.
> 
> [!!!플레이터로더.zip](https://github.com/user-attachments/files/20180281/PlaterLoader.zip)

I've tried using it, but the glow still doesn't work. The glow works in Hekili though.

**Comment by chomg88** [comment]
> > Hekili는 weakauras 애드온을 종속성으로 사용할 가능성이 높으며 이로 인해 weakauras 애드온이 plater보다 먼저 로드됩니다. platerloader 애드온을 설치하면 문제가 해결될 것입니다.
> > [!!!플레이터로더.zip](https://github.com/user-attachments/files/20180281/PlaterLoader.zip)
> 
> I've tried using it, but the glow still doesn't work. The glow works in Hekili though.

That's unfortunate. I had the same issue, but I found a solution by asking in the Liquid WeakAura Discord

**Comment by Hekili** [comment]
I'm interested to know if changing the whole header section (prefixed with `##`) in Hekili.toc will resolve this for y'all:

```
## Interface: 110105
## Version: @project-version@
## Title: Hekili
## Author: Hekili
## IconTexture: Interface\AddOns\Hekili\Textures\LOGO-ORANGE.blp
## Notes: Priority helper based on SimulationCraft action lists.
## SavedVariables: HekiliDB
## OptionalDeps: AddOnSkins, ButtonForge, ConsolePort, ElvUI, LibDualSpec-1.0, Masque
## X-Curse-Project-ID: 69254
## X-WoWI-ID: 24608
## X-Wago-ID: WYK9WXNL
```

The change made is just removing WeakAuras from the OptionalDeps line.

**Comment by less1140** [comment]
> I'm interested to know if changing the whole header section (prefixed with `##`) in Hekili.toc will resolve this for y'all:
> 
> ```
> ## Interface: 110105
> ## Version: @project-version@
> ## Title: Hekili
> ## Author: Hekili
> ## IconTexture: Interface\AddOns\Hekili\Textures\LOGO-ORANGE.blp
> ## Notes: Priority helper based on SimulationCraft action lists.
> ## SavedVariables: HekiliDB
> ## OptionalDeps: AddOnSkins, ButtonForge, ConsolePort, ElvUI, LibDualSpec-1.0, Masque
> ## X-Curse-Project-ID: 69254
> ## X-WoWI-ID: 24608
> ## X-Wago-ID: WYK9WXNL
> ```
> 
> The change made is just removing WeakAuras from the OptionalDeps line.

I’ve modified the file as you suggested by removing WeakAuras from the OptionalDeps line in Hekili.toc. I’ll test it and follow up with a comment after confirming the results.

**Comment by less1140** [comment]
> I'm interested to know if changing the whole header section (prefixed with `##`) in Hekili.toc will resolve this for y'all:
> 
> ```
> ## Interface: 110105
> ## Version: @project-version@
> ## Title: Hekili
> ## Author: Hekili
> ## IconTexture: Interface\AddOns\Hekili\Textures\LOGO-ORANGE.blp
> ## Notes: Priority helper based on SimulationCraft action lists.
> ## SavedVariables: HekiliDB
> ## OptionalDeps: AddOnSkins, ButtonForge, ConsolePort, ElvUI, LibDualSpec-1.0, Masque
> ## X-Curse-Project-ID: 69254
> ## X-WoWI-ID: 24608
> ## X-Wago-ID: WYK9WXNL
> ```
> 
> The change made is just removing WeakAuras from the OptionalDeps line.

After installing !!!PlaterLoader.zip and removing WeakAuras from the OptionalDeps line in Hekili.toc as suggested, the issue still persists. The glow effect is still being triggered by Hekili during the One-Armed Bandit prize mechanic when using the Liquid WeakAura — coin adds continue to show nameplate glows
