### ISSUE TITLE
[REC] ⚠️ Deathstalker Sub Rogue - Addon never suggests using Eviscerate

### ISSUE THREAD

**Issue by aaronepaine-dotcom** [Hekili/hekili#5035]
### Before You Begin

- [x] I confirm I am using the latest version of the addon (outdated versions may have problems that were fixed on the newest release).
- [x] I confirm I am playing on official Blizzard servers (not private servers).
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [x] I have updated the issue title to clearly describe the problem.
- [x] I am reporting an issue with the default specialization priority (not a custom or imported priority).

### Specialization

Rogue - subtlety

### Describe the Issue

For my Subtelty Rogue - The addon is constantly suggesting backstab, or other combo generating abilities and never shows that Eviscerate should be used even with full combo points.  Never happened before 11.2 update.

### How to Reproduce

1.  Enter game as Sub Rogue.
2. Spec as Deathstalker
3. Enter stealth
4. Activate Shadow Dance, Shadow Blades, Symbols, etc
5. Cheap Shot Target Dummy, and begin rotation.

### What is your information source?

Based on my in-game experience and intuition

### Snapshot (Link)

https://pastebin.com/6QwEfe0B

### Contact Information

_paine.

**Comment by Naessah-GH** [comment]
The issue is also with Trickster. When it happens u have to disable Major Cooldown and then the finisher show up and the rotation continue.
I'm trying to know why but i'm lost

**Comment by syrifgit** [comment]
Please provide a raidbots quick sim as per the ticket instructions.

**Comment by aaronepaine-dotcom** [comment]
https://www.raidbots.com/simbot/report/iCBUELTJ4dxTTtpPq7NaFu

Hopefully I did this right...but weird even a Quick Sim shows no Eviscerates....

**Comment by Zifrost** [comment]
I dont know whats wrong with ur sim
If u use 5 min Eviscerate pop up like my sim https://www.raidbots.com/simbot/report/hXJ9GZiwdp2XhJdtMtsQ7x
Even in my 1min sim it show up https://www.raidbots.com/simbot/report/njPBnzWbK3x4Kvx7SeTLcA

**Comment by Naessah-GH** [comment]
> I dont know whats wrong with ur sim If u use 5 min Eviscerate pop up like my sim https://www.raidbots.com/simbot/report/hXJ9GZiwdp2XhJdtMtsQ7x Even in my 1min sim it show up https://www.raidbots.com/simbot/report/njPBnzWbK3x4Kvx7SeTLcA

Raidbot have a problem with Deathstalker, it doesn't sim correctly. Your sims are Trickster not Deathstalker, thats why they show Evisc.

Deathstalker: https://www.raidbots.com/simbot/report/wn6TBT3jF1NAcasmQ8xHa5
<img width="586" height="272" alt="Image" src="https://github.com/user-attachments/assets/0c80821d-e6ac-485a-b9d8-863a3318dfad" />

Trickster: https://www.raidbots.com/simbot/report/h7VmujAth1E6cGw1vVCNrh
<img width="589" height="267" alt="Image" src="https://github.com/user-attachments/assets/a0d3261d-cb51-4a23-9569-6d05c58a9359" />

But anyway, the problem is in game, sometimes finishers aren't recommended and Hekili keep recommending backtab even if you are already full CP. In both Deathstalker & Trickster. Using the latest build.
Sometime disabling Major Cooldown toggle let Hekili show Finishers instead of builder, but sometime it doesn't help. Strange

**Comment by aaronepaine-dotcom** [comment]
Agreed, I have a similar issue with my Boomkin where it's not suggesting Starsurge during Incarn.  Seems as if Blizzard has messed something up...

**Comment by syrifgit** [comment]
> Agreed, I have a similar issue with my Boomkin where it's not suggesting Starsurge during Incarn. Seems as if Blizzard has messed something up...

Completely unrelated to this ticket and unrelated to blizzard "messing something up".

Druid is not updated for 11.2, please refer to: https://github.com/Hekili/hekili/issues/5010

**Comment by aaronepaine-dotcom** [comment]
> > Agreed, I have a similar issue with my Boomkin where it's not suggesting Starsurge during Incarn. Seems as if Blizzard has messed something up...
> 
> Completely unrelated to this ticket and unrelated to blizzard "messing something up".
> 
> Druid is not updated for 11.2, please refer to: [#5010](https://github.com/Hekili/hekili/issues/5010)

My apologies, I'll stay on task with this ticket.

**Comment by syrifgit** [comment]
Should be fixed in the next addon update. Was an error with builds that didn't take the flagellation talent.

**Comment by aaronepaine-dotcom** [comment]
> Should be fixed in the next addon update. Was an error with builds that didn't take the flagellation talent.

Excellent, thank you for digging into this!

**Comment by Naessah-GH** [comment]
> Should be fixed in the next addon update. Was an error with builds that didn't take the flagellation talent.

Hey, thank you

But the problem persist for the other hero talent (Trickster), and we are using Flagellation talent.

**Comment by syrifgit** [comment]
> > Should be fixed in the next addon update. Was an error with builds that didn't take the flagellation talent.
> 
> Hey, thank you
> 
> But the problem persist for the other hero talent (Trickster), and we are using Flagellation talent.

Then you should provide a snapshot of that happening while using those talents for us so it can be diagnosed

**Comment by Naessah-GH** [comment]
Theres the Snapshot
Recommendations 2 and 3 are at 7 CP and still recommand Backstab instead of Evisc.

I can read this for Evisc check "The action is not ready ( 3600.00 ) before our maximum delay window ( 8.57 ) for this query."

From what I understand, Evisc isn't ready because it's Coup de Grace.
But Coup de Grace isn't ok because Flagellation is ready , and the Coup de Grace condition is:
debuff.fazed.up & ( **cooldown.flagellation.remains >= 20** | ! talent.flagellation.enabled ) | fight_remains <= 10

Start thinking Flagellation was the recommandation but since backstab is in the end (filler) it overhide, and became the recommended spell


[Snapshot.txt](https://github.com/user-attachments/files/21670968/Snapshot.txt)

**Comment by syrifgit** [comment]
The sims also do this, I will bring it up with the theorycrafter.

**Comment by Naessah-GH** [comment]
If I correctly understand the snapshot, Flagellation was the recommended spell but got erased by Backstab whois like in the end of the list

So Eviscerate isn't recommended because the spell changed for Coup de Grace
Coup de Grace isn't recommended because Flagellation is ready
Flagellation is recommended but got erased by Backstab at the most end of the checks
Then it recommend Backstab
It does (@7 CP) Backstab > Backstab instead of Flagellation > Coup de Grace

It only happens when Flagellation is ready, thats why disabling Major CD help to get a finisher recommendation since he's on Major CD

**20.**  flagellation ( cds - 6 )
        The action (flagellation) is usable at (4.14 + 4.43).
         - the action is ready before the current recommendation (at +4.43 vs. +15.00).
        List ( cds ) called from ( Subtlety:default:9 ) would PASS at 4.43.
        NONE
         - this entry's criteria PASSES: combo_points.current[7.00] >= 5 & cooldown.shadow_blades.remains[2.61] <= 3 | raid[false] & boss[false] & fight_remains[171.43] <= 25
        Action chosen:  flagellation at 4.43!
        Texture shown:  6035318
        Time spent on this action:  0.13ms
        TimeData:Subtlety-cds-6:flagellation:x0:0.13:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.02):Pre-Script(0.00):Post-Script(0.01):Post Recheck(0.02):Action Stored(0.01)
        Exiting cds with recommendation of flagellation at +4.43s.
        Returned from list (cds), **current recommendation is flagellation (+4.43).**
        - cds
...
**56.**  backstab ( build - 13 )
        The action (backstab) is usable at (4.14 + 3.34) with cost of 40 energy (have 40).
         - the action is ready before the current recommendation (at +3.34 vs. +4.43).
        List ( build ) called from ( Subtlety:default:21 ) would PASS at 3.34.
        NONE
         - this entry has no criteria to test.
        Action chosen:  backstab at 3.34!
        Texture shown:  %s
        Time spent on this action:  0.08ms
        TimeData:Subtlety-build-13:backstab:x0:0.08:Ability Known, Enabled(0.02):Post-TTR and Essential(0.02):Post Cycle(0.00):Post Usable(0.00):Post Ready/Clash(0.01):Post Stack(0.01):Post Recheck(0.00):Action Stored(0.01)
        Exiting build with recommendation of backstab at +3.34s.
        Returned from list (build), **current recommendation is backstab (+3.34).**
        - build

**Comment by syrifgit** [comment]
Yes. You would've had to wait 4.4 seconds to cast flag. So instead of AFKing for 4.4 seconds, it chose to backstab. Which is correct, according to Fuu the guidewriter / APL writer.

**Comment by Naessah-GH** [comment]
> Yes. You would've had to wait 4.4 seconds to cast flag. So instead of AFKing for 4.4 seconds, it chose to backstab. Which is correct, according to Fuu the guidewriter / APL writer.

Ok, seem's strange to double or triple cast backstab when full CP but if its the best option, I understand

**Comment by syrifgit** [comment]
You can read more about it in the Rogue discord.
