### ISSUE TITLE
[REC] Feral - Convoke is recommanded before Tiger's Fury.

### ISSUE THREAD

**Issue by MistDZX** [Hekili/hekili#5070]
### Before You Begin

- [x] I confirm I am using the latest version of the addon (outdated versions may have problems that were fixed on the newest release).
- [x] I confirm I am playing on official Blizzard servers (not private servers).
- [x] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [x] I have updated the issue title to clearly describe the problem.
- [x] I am reporting an issue with the default specialization priority (not a custom or imported priority).

### Specialization

Druid - Feral

### Describe the Issue

It seems that Tiger’s Fury is no longer a priority in the rotation. Hekili sometimes suggests Convoke before Tiger’s Fury (not all the time), and when Tiger’s Fury is just a few seconds from being available, it tells me to use Convoke first and then Tiger’s Fury.

### How to Reproduce

Try using Tiger’s Fury without Convoke and see what happens.

### What is your information source?

Based on my in-game experience and intuition

### Snapshot (Link)

https://pastebin.com/vT23QVbu

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/rReCEHwosxPZNHaBPzcPBD

**Comment by Hekili** [comment]
The priority tries to sync with Berserk / Incarnation, not specifically Tiger's Fury, otherwise uses roughly on cooldown.  The assumption is you'd probably sync Tiger's Fury with Berserk / Incarnation, but you don't want to sit on Convoke forever if you didn't sync them.

**Comment by MistDZX** [comment]
Strange, because before the 11.2 update, Hekili always used to wait for Tiger’s Fury before using Convoke. Also, in every sim I’ve made, Tiger’s Fury always comes before Convoke.
Also, in all the tests I’ve done on training dummies, using Convoke before Tiger’s Fury is always a DPS loss — even if it means waiting 15 seconds for the tiger's fury cooldown. Very strange.

**Comment by syrifgit** [comment]
This was likely caused by the lua error which has been fixed in the newest release today. I imagine updating your addon will show the rotation behaving more as expected.

**Comment by MistDZX** [comment]
Still not the case sadly ^.^
Also, Rip is always prefered over Ferocious Bite, even if the DoT is already on the target. We almsot never Ferocious Bite if we follow Hekili

**Comment by MistDZX** [comment]
Also, Rip is always prefered over Ferocious Bite, even if the DoT is already on the target.

**Comment by ctroller** [comment]
Rip issue already has an open Ticket: https://github.com/Hekili/hekili/issues/5080
